@startuml

class Product {
    price: double
    name: String
}

interface DiscountCalculator {
    +calculateDiscounts(products: List<Product>, totalDiscount: double): List<Double>
}
class App {
    products: List<Product>
    calculator: DiscountCalculator
    +readProductsFromInput(scanner: Scanner)
    +calculateAndPrintDiscounts()
}

class ProportionalCalculator

DiscountCalculator <|.. ProportionalCalculator
App -> DiscountCalculator
App *-- Product


@enduml